name: Health Check

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes
  workflow_dispatch:       # 👈 Allows manual trigger

jobs:
  run-health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use a compatible Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Run Health Check Script
        run: node healthCheck.js
